# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_HelperDoc(object):
    def setupUi(self, HelperDoc):
        HelperDoc.setObjectName("HelperDoc")
        HelperDoc.resize(1321, 893)
        HelperDoc.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        HelperDoc.setAutoFillBackground(False)
        HelperDoc.setStyleSheet("background-color: #181818;")
        self.centralwidget = QtWidgets.QWidget(HelperDoc)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 800))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -977, 381, 1850))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 1850))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 20000))
        self.frame.setMinimumSize(QtCore.QSize(400, 1880))
        self.frame.setMaximumSize(QtCore.QSize(400, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.add_row = QtWidgets.QPushButton(self.frame)
        self.add_row.setGeometry(QtCore.QRect(200, 1750, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.add_row.setFont(font)
        self.add_row.setStyleSheet("QPushButton {\n"
"    background-color: #2C2C2C;\n"
"    color: #fff;\n"
"    text-align: center;\n"
"    padding-bottom: 1px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3F3F3F;\n"
"}")
        self.add_row.setObjectName("add_row")
        self.title_doc_line = QtWidgets.QLineEdit(self.frame)
        self.title_doc_line.setGeometry(QtCore.QRect(50, 70, 271, 31))
        self.title_doc_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.title_doc_line.setText("")
        self.title_doc_line.setObjectName("title_doc_line")
        self.title_doc = QtWidgets.QLabel(self.frame)
        self.title_doc.setGeometry(QtCore.QRect(50, 50, 141, 16))
        self.title_doc.setStyleSheet("color: #fff;")
        self.title_doc.setObjectName("title_doc")
        self.type_doc_line = QtWidgets.QLineEdit(self.frame)
        self.type_doc_line.setGeometry(QtCore.QRect(50, 130, 271, 31))
        self.type_doc_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.type_doc_line.setText("")
        self.type_doc_line.setObjectName("type_doc_line")
        self.type_doc = QtWidgets.QLabel(self.frame)
        self.type_doc.setGeometry(QtCore.QRect(50, 110, 141, 16))
        self.type_doc.setStyleSheet("color: #fff;")
        self.type_doc.setObjectName("type_doc")
        self.status_doc_line = QtWidgets.QLineEdit(self.frame)
        self.status_doc_line.setGeometry(QtCore.QRect(50, 190, 271, 31))
        self.status_doc_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.status_doc_line.setObjectName("status_doc_line")
        self.status_doc = QtWidgets.QLabel(self.frame)
        self.status_doc.setGeometry(QtCore.QRect(50, 170, 141, 16))
        self.status_doc.setStyleSheet("color: #fff;")
        self.status_doc.setObjectName("status_doc")
        self.loss_confirmation = QtWidgets.QLabel(self.frame)
        self.loss_confirmation.setGeometry(QtCore.QRect(50, 230, 141, 16))
        self.loss_confirmation.setStyleSheet("color: #fff;")
        self.loss_confirmation.setObjectName("loss_confirmation")
        self.loss_confirmation_line = QtWidgets.QLineEdit(self.frame)
        self.loss_confirmation_line.setGeometry(QtCore.QRect(50, 250, 271, 31))
        self.loss_confirmation_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.loss_confirmation_line.setObjectName("loss_confirmation_line")
        self.confirmation_exchange_line = QtWidgets.QLineEdit(self.frame)
        self.confirmation_exchange_line.setGeometry(QtCore.QRect(50, 310, 271, 31))
        self.confirmation_exchange_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.confirmation_exchange_line.setObjectName("confirmation_exchange_line")
        self.confirmation_exchange = QtWidgets.QLabel(self.frame)
        self.confirmation_exchange.setGeometry(QtCore.QRect(50, 290, 141, 16))
        self.confirmation_exchange.setStyleSheet("color: #fff;")
        self.confirmation_exchange.setObjectName("confirmation_exchange")
        self.destruction_confirmation_line = QtWidgets.QLineEdit(self.frame)
        self.destruction_confirmation_line.setGeometry(QtCore.QRect(50, 370, 271, 31))
        self.destruction_confirmation_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.destruction_confirmation_line.setObjectName("destruction_confirmation_line")
        self.destruction_confirmation = QtWidgets.QLabel(self.frame)
        self.destruction_confirmation.setGeometry(QtCore.QRect(50, 350, 161, 16))
        self.destruction_confirmation.setStyleSheet("color: #fff;")
        self.destruction_confirmation.setObjectName("destruction_confirmation")
        self.education_level = QtWidgets.QLabel(self.frame)
        self.education_level.setGeometry(QtCore.QRect(50, 410, 161, 16))
        self.education_level.setStyleSheet("color: #fff;")
        self.education_level.setObjectName("education_level")
        self.education_level_line = QtWidgets.QLineEdit(self.frame)
        self.education_level_line.setGeometry(QtCore.QRect(50, 430, 271, 31))
        self.education_level_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.education_level_line.setObjectName("education_level_line")
        self.series_doc_line = QtWidgets.QLineEdit(self.frame)
        self.series_doc_line.setGeometry(QtCore.QRect(50, 490, 271, 31))
        self.series_doc_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.series_doc_line.setObjectName("series_doc_line")
        self.series_doc = QtWidgets.QLabel(self.frame)
        self.series_doc.setGeometry(QtCore.QRect(50, 470, 161, 16))
        self.series_doc.setStyleSheet("color: #fff;")
        self.series_doc.setObjectName("series_doc")
        self.number_doc_line = QtWidgets.QLineEdit(self.frame)
        self.number_doc_line.setGeometry(QtCore.QRect(50, 550, 271, 31))
        self.number_doc_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.number_doc_line.setObjectName("number_doc_line")
        self.number_doc = QtWidgets.QLabel(self.frame)
        self.number_doc.setGeometry(QtCore.QRect(50, 530, 161, 16))
        self.number_doc.setStyleSheet("color: #fff;")
        self.number_doc.setObjectName("number_doc")
        self.issue_date = QtWidgets.QLabel(self.frame)
        self.issue_date.setGeometry(QtCore.QRect(50, 590, 161, 16))
        self.issue_date.setStyleSheet("color: #fff;")
        self.issue_date.setObjectName("issue_date")
        self.issue_date_line = QtWidgets.QLineEdit(self.frame)
        self.issue_date_line.setGeometry(QtCore.QRect(50, 610, 271, 31))
        self.issue_date_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.issue_date_line.setObjectName("issue_date_line")
        self.registration_number_line = QtWidgets.QLineEdit(self.frame)
        self.registration_number_line.setGeometry(QtCore.QRect(50, 670, 271, 31))
        self.registration_number_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.registration_number_line.setObjectName("registration_number_line")
        self.registration_number = QtWidgets.QLabel(self.frame)
        self.registration_number.setGeometry(QtCore.QRect(50, 650, 161, 16))
        self.registration_number.setStyleSheet("color: #fff;")
        self.registration_number.setObjectName("registration_number")
        self.code_profession_line = QtWidgets.QLineEdit(self.frame)
        self.code_profession_line.setGeometry(QtCore.QRect(50, 730, 271, 31))
        self.code_profession_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.code_profession_line.setObjectName("code_profession_line")
        self.title_profession_line = QtWidgets.QLineEdit(self.frame)
        self.title_profession_line.setGeometry(QtCore.QRect(50, 790, 271, 31))
        self.title_profession_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.title_profession_line.setObjectName("title_profession_line")
        self.code_profession = QtWidgets.QLabel(self.frame)
        self.code_profession.setGeometry(QtCore.QRect(50, 710, 251, 16))
        self.code_profession.setStyleSheet("color: #fff;")
        self.code_profession.setObjectName("code_profession")
        self.title_qualification_line = QtWidgets.QLineEdit(self.frame)
        self.title_qualification_line.setGeometry(QtCore.QRect(50, 850, 271, 31))
        self.title_qualification_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.title_qualification_line.setObjectName("title_qualification_line")
        self.education_program_line = QtWidgets.QLineEdit(self.frame)
        self.education_program_line.setGeometry(QtCore.QRect(50, 910, 271, 31))
        self.education_program_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.education_program_line.setObjectName("education_program_line")
        self.title_profession = QtWidgets.QLabel(self.frame)
        self.title_profession.setGeometry(QtCore.QRect(50, 770, 251, 16))
        self.title_profession.setStyleSheet("color: #fff;")
        self.title_profession.setObjectName("title_profession")
        self.title_qualification = QtWidgets.QLabel(self.frame)
        self.title_qualification.setGeometry(QtCore.QRect(50, 830, 251, 16))
        self.title_qualification.setStyleSheet("color: #fff;")
        self.title_qualification.setObjectName("title_qualification")
        self.education_program = QtWidgets.QLabel(self.frame)
        self.education_program.setGeometry(QtCore.QRect(50, 890, 251, 16))
        self.education_program.setStyleSheet("color: #fff;")
        self.education_program.setObjectName("education_program")
        self.admission_year_line = QtWidgets.QLineEdit(self.frame)
        self.admission_year_line.setGeometry(QtCore.QRect(50, 970, 271, 31))
        self.admission_year_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.admission_year_line.setObjectName("admission_year_line")
        self.graduation_year_line = QtWidgets.QLineEdit(self.frame)
        self.graduation_year_line.setGeometry(QtCore.QRect(50, 1030, 271, 31))
        self.graduation_year_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.graduation_year_line.setObjectName("graduation_year_line")
        self.study_period_line = QtWidgets.QLineEdit(self.frame)
        self.study_period_line.setGeometry(QtCore.QRect(50, 1090, 271, 31))
        self.study_period_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.study_period_line.setObjectName("study_period_line")
        self.admission_year = QtWidgets.QLabel(self.frame)
        self.admission_year.setGeometry(QtCore.QRect(50, 950, 251, 16))
        self.admission_year.setStyleSheet("color: #fff;")
        self.admission_year.setObjectName("admission_year")
        self.graduation_year = QtWidgets.QLabel(self.frame)
        self.graduation_year.setGeometry(QtCore.QRect(50, 1010, 251, 16))
        self.graduation_year.setStyleSheet("color: #fff;")
        self.graduation_year.setObjectName("graduation_year")
        self.study_period = QtWidgets.QLabel(self.frame)
        self.study_period.setGeometry(QtCore.QRect(50, 1070, 251, 16))
        self.study_period.setStyleSheet("color: #fff;")
        self.study_period.setObjectName("study_period")
        self.last_name_line = QtWidgets.QLineEdit(self.frame)
        self.last_name_line.setGeometry(QtCore.QRect(50, 1150, 271, 31))
        self.last_name_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.last_name_line.setObjectName("last_name_line")
        self.name_line = QtWidgets.QLineEdit(self.frame)
        self.name_line.setGeometry(QtCore.QRect(50, 1210, 271, 31))
        self.name_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.name_line.setObjectName("name_line")
        self.middle_name_line = QtWidgets.QLineEdit(self.frame)
        self.middle_name_line.setGeometry(QtCore.QRect(50, 1270, 271, 31))
        self.middle_name_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.middle_name_line.setObjectName("middle_name_line")
        self.birth_date_line = QtWidgets.QLineEdit(self.frame)
        self.birth_date_line.setGeometry(QtCore.QRect(50, 1330, 271, 31))
        self.birth_date_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.birth_date_line.setObjectName("birth_date_line")
        self.gender_line = QtWidgets.QLineEdit(self.frame)
        self.gender_line.setGeometry(QtCore.QRect(50, 1390, 271, 31))
        self.gender_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.gender_line.setObjectName("gender_line")
        self.snills_line = QtWidgets.QLineEdit(self.frame)
        self.snills_line.setGeometry(QtCore.QRect(50, 1450, 271, 31))
        self.snills_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.snills_line.setObjectName("snills_line")
        self.last_name = QtWidgets.QLabel(self.frame)
        self.last_name.setGeometry(QtCore.QRect(50, 1130, 251, 16))
        self.last_name.setStyleSheet("color: #fff;")
        self.last_name.setObjectName("last_name")
        self.name = QtWidgets.QLabel(self.frame)
        self.name.setGeometry(QtCore.QRect(50, 1190, 251, 16))
        self.name.setStyleSheet("color: #fff;")
        self.name.setObjectName("name")
        self.middle_name = QtWidgets.QLabel(self.frame)
        self.middle_name.setGeometry(QtCore.QRect(50, 1250, 251, 16))
        self.middle_name.setStyleSheet("color: #fff;")
        self.middle_name.setObjectName("middle_name")
        self.birth_date = QtWidgets.QLabel(self.frame)
        self.birth_date.setGeometry(QtCore.QRect(50, 1310, 251, 16))
        self.birth_date.setStyleSheet("color: #fff;")
        self.birth_date.setObjectName("birth_date")
        self.gender = QtWidgets.QLabel(self.frame)
        self.gender.setGeometry(QtCore.QRect(50, 1370, 251, 16))
        self.gender.setStyleSheet("color: #fff;")
        self.gender.setObjectName("gender")
        self.snills = QtWidgets.QLabel(self.frame)
        self.snills.setGeometry(QtCore.QRect(50, 1430, 251, 16))
        self.snills.setStyleSheet("color: #fff;")
        self.snills.setObjectName("snills")
        self.country_code_line = QtWidgets.QLineEdit(self.frame)
        self.country_code_line.setGeometry(QtCore.QRect(50, 1510, 271, 31))
        self.country_code_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.country_code_line.setObjectName("country_code_line")
        self.education_form_line = QtWidgets.QLineEdit(self.frame)
        self.education_form_line.setGeometry(QtCore.QRect(50, 1570, 271, 31))
        self.education_form_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.education_form_line.setObjectName("education_form_line")
        self.education_receipt_form_line = QtWidgets.QLineEdit(self.frame)
        self.education_receipt_form_line.setGeometry(QtCore.QRect(50, 1630, 271, 31))
        self.education_receipt_form_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.education_receipt_form_line.setObjectName("education_receipt_form_line")
        self.financing_source_line = QtWidgets.QLineEdit(self.frame)
        self.financing_source_line.setGeometry(QtCore.QRect(50, 1690, 271, 31))
        self.financing_source_line.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.financing_source_line.setObjectName("financing_source_line")
        self.country_code = QtWidgets.QLabel(self.frame)
        self.country_code.setGeometry(QtCore.QRect(50, 1490, 291, 16))
        self.country_code.setStyleSheet("color: #fff;")
        self.country_code.setObjectName("country_code")
        self.education_form = QtWidgets.QLabel(self.frame)
        self.education_form.setGeometry(QtCore.QRect(50, 1550, 251, 16))
        self.education_form.setStyleSheet("color: #fff;")
        self.education_form.setObjectName("education_form")
        self.education_receipt_form = QtWidgets.QLabel(self.frame)
        self.education_receipt_form.setGeometry(QtCore.QRect(50, 1610, 251, 21))
        self.education_receipt_form.setStyleSheet("color: #fff;")
        self.education_receipt_form.setObjectName("education_receipt_form")
        self.financing_source = QtWidgets.QLabel(self.frame)
        self.financing_source.setGeometry(QtCore.QRect(50, 1670, 251, 16))
        self.financing_source.setStyleSheet("color: #fff;")
        self.financing_source.setObjectName("financing_source")
        self.clear = QtWidgets.QPushButton(self.frame)
        self.clear.setGeometry(QtCore.QRect(70, 1750, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.clear.setFont(font)
        self.clear.setStyleSheet("QPushButton {\n"
"    background-color: #2C2C2C;\n"
"    color: #fff;\n"
"    text-align: center;\n"
"    padding-bottom: 1px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3F3F3F;\n"
"}")
        self.clear.setObjectName("clear")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(900, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.table = QtWidgets.QTableWidget(self.frame_2)
        self.table.setGeometry(QtCore.QRect(0, 140, 901, 601))
        self.table.setBaseSize(QtCore.QSize(0, 0))
        self.table.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.table.setStyleSheet("background-color: #fff;")
        self.table.setObjectName("table")
        self.table.setColumnCount(28)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(27, item)
        self.suggest_input = QtWidgets.QLineEdit(self.frame_2)
        self.suggest_input.setGeometry(QtCore.QRect(170, 70, 511, 31))
        self.suggest_input.setStyleSheet("QLineEdit {\n"
"    color: #fff;\n"
"    padding-left: 10px;\n"
"}")
        self.suggest_input.setText("")
        self.suggest_input.setObjectName("suggest_input")
        self.remove_row = QtWidgets.QPushButton(self.frame_2)
        self.remove_row.setGeometry(QtCore.QRect(340, 790, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.remove_row.setFont(font)
        self.remove_row.setStyleSheet("QPushButton {\n"
"    background-color: #2C2C2C;\n"
"    color: #fff;\n"
"    text-align: center;\n"
"    padding-bottom: 1px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3F3F3F;\n"
"}")
        self.remove_row.setObjectName("remove_row")
        self.suggest_input_button = QtWidgets.QPushButton(self.frame_2)
        self.suggest_input_button.setGeometry(QtCore.QRect(690, 70, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.suggest_input_button.setFont(font)
        self.suggest_input_button.setStyleSheet("QPushButton {\n"
"    background-color: #2C2C2C;\n"
"    color: #fff;\n"
"    text-align: center;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3F3F3F;\n"
"}")
        self.suggest_input_button.setObjectName("suggest_input_button")
        self.create_doc = QtWidgets.QPushButton(self.frame_2)
        self.create_doc.setGeometry(QtCore.QRect(480, 790, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.create_doc.setFont(font)
        self.create_doc.setStyleSheet("QPushButton {\n"
"    background-color: #2C2C2C;\n"
"    color: #fff;\n"
"    text-align: center;\n"
"    padding-bottom: 1px;\n"
"    border: 0;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #353535;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3F3F3F;\n"
"}")
        self.create_doc.setObjectName("create_doc")
        self.horizontalLayout.addWidget(self.frame_2)
        HelperDoc.setCentralWidget(self.centralwidget)

        self.retranslateUi(HelperDoc)
        QtCore.QMetaObject.connectSlotsByName(HelperDoc)

    def retranslateUi(self, HelperDoc):
        _translate = QtCore.QCoreApplication.translate
        HelperDoc.setWindowTitle(_translate("HelperDoc", "MainWindow"))
        self.add_row.setText(_translate("HelperDoc", "Добавить"))
        self.title_doc.setText(_translate("HelperDoc", "Наименование документа"))
        self.type_doc.setText(_translate("HelperDoc", "Вид документа"))
        self.status_doc.setText(_translate("HelperDoc", "Статус документа"))
        self.loss_confirmation.setText(_translate("HelperDoc", "Подтверждение утраты"))
        self.confirmation_exchange.setText(_translate("HelperDoc", "Подтверждение обмена"))
        self.destruction_confirmation.setText(_translate("HelperDoc", "Подтверждение  уничтожения"))
        self.education_level.setText(_translate("HelperDoc", "Уровень образования"))
        self.series_doc.setText(_translate("HelperDoc", "Серия документа"))
        self.number_doc.setText(_translate("HelperDoc", "Номер документа"))
        self.issue_date.setText(_translate("HelperDoc", "Дата выдачи"))
        self.registration_number.setText(_translate("HelperDoc", "Регистрационный номер"))
        self.code_profession.setText(_translate("HelperDoc", "Код профессии, специальности"))
        self.title_profession.setText(_translate("HelperDoc", "Наименование профессии, специальности"))
        self.title_qualification.setText(_translate("HelperDoc", "Наименование квалификации"))
        self.education_program.setText(_translate("HelperDoc", "Наименование образовательной программы"))
        self.admission_year.setText(_translate("HelperDoc", "Год поступления"))
        self.graduation_year.setText(_translate("HelperDoc", "Год окончания"))
        self.study_period.setText(_translate("HelperDoc", "Срок обучения, лет"))
        self.last_name.setText(_translate("HelperDoc", "Фамилия получателя"))
        self.name.setText(_translate("HelperDoc", "Имя получателя"))
        self.middle_name.setText(_translate("HelperDoc", "Отчество получателя"))
        self.birth_date.setText(_translate("HelperDoc", "Дата рождения получателя"))
        self.gender.setText(_translate("HelperDoc", "Пол получателя"))
        self.snills.setText(_translate("HelperDoc", "СНИЛС"))
        self.country_code.setText(_translate("HelperDoc", "Гражданство получателя (код страны по ОКСМ)"))
        self.education_form.setText(_translate("HelperDoc", "Форма обучения"))
        self.education_receipt_form.setText(_translate("HelperDoc", "<html><head/><body><p>Форма получения образования</p></body></html>"))
        self.financing_source.setText(_translate("HelperDoc", "Источник финансирования обучения"))
        self.clear.setText(_translate("HelperDoc", "Очистить"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("HelperDoc", "Наименование документа"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("HelperDoc", "Вид документа"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("HelperDoc", "Статус документа"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("HelperDoc", "Подтверждение утраты"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("HelperDoc", "Подтверждение обмена "))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("HelperDoc", "Подтверждение уничтожения"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("HelperDoc", "Уровень образования"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("HelperDoc", "Серия документа"))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("HelperDoc", "Номер документа"))
        item = self.table.horizontalHeaderItem(9)
        item.setText(_translate("HelperDoc", "Дата выдачи"))
        item = self.table.horizontalHeaderItem(10)
        item.setText(_translate("HelperDoc", "Регистрационный номер"))
        item = self.table.horizontalHeaderItem(11)
        item.setText(_translate("HelperDoc", "Код профессии, специальности"))
        item = self.table.horizontalHeaderItem(12)
        item.setText(_translate("HelperDoc", "Наименование профессии, специальности"))
        item = self.table.horizontalHeaderItem(13)
        item.setText(_translate("HelperDoc", "Наименование квалификации"))
        item = self.table.horizontalHeaderItem(14)
        item.setText(_translate("HelperDoc", "Наименование образовательной  программы"))
        item = self.table.horizontalHeaderItem(15)
        item.setText(_translate("HelperDoc", "Год поступления"))
        item = self.table.horizontalHeaderItem(16)
        item.setText(_translate("HelperDoc", "Год окончания"))
        item = self.table.horizontalHeaderItem(17)
        item.setText(_translate("HelperDoc", "Срок обучения, лет"))
        item = self.table.horizontalHeaderItem(18)
        item.setText(_translate("HelperDoc", "Фамилия получателя"))
        item = self.table.horizontalHeaderItem(19)
        item.setText(_translate("HelperDoc", "Имя получателя"))
        item = self.table.horizontalHeaderItem(20)
        item.setText(_translate("HelperDoc", "Отчество получателя"))
        item = self.table.horizontalHeaderItem(21)
        item.setText(_translate("HelperDoc", "Дата рождения получателя "))
        item = self.table.horizontalHeaderItem(22)
        item.setText(_translate("HelperDoc", "Пол получателя"))
        item = self.table.horizontalHeaderItem(23)
        item.setText(_translate("HelperDoc", "СНИЛС"))
        item = self.table.horizontalHeaderItem(24)
        item.setText(_translate("HelperDoc", "Гражданство получателя (код страны по ОКСМ)"))
        item = self.table.horizontalHeaderItem(25)
        item.setText(_translate("HelperDoc", "Форма обучения"))
        item = self.table.horizontalHeaderItem(26)
        item.setText(_translate("HelperDoc", "Форма получения образования на момент прекращения образовательных отношений"))
        item = self.table.horizontalHeaderItem(27)
        item.setText(_translate("HelperDoc", "Источник финансирования обучения"))
        self.remove_row.setText(_translate("HelperDoc", "Удалить"))
        self.suggest_input_button.setText(_translate("HelperDoc", "Искать"))
        self.create_doc.setText(_translate("HelperDoc", "Создать документ"))
